{{- range $name, $build := $.Values.builds }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "build name is required" $name }}
  labels:
    {{- include "imagebuilder.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "imagebuilder.labels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "imagebuilder.labels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "imagebuilder.serviceAccountName" $ }}
      restartPolicy: Always
      containers:
        - name: "{{ $name }}"
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 2592000; done"]
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: source
            mountPath: /workspace
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
        - name: git-sync
          image: "{{ $.Values.image.gitsynce.repository }}:{{ $.Values.image.gitsynce.tag }}"
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["all"]
          volumeMounts:
          - name: source
            mountPath: /workspace
          - name: git-creds
            mountPath: /etc/git-secret
          env:
          - name: GIT_SYNC_REPO
            value: "{{ required "git repo is required" $build.git.repo }}"
          - name: GIT_SYNC_BRANCH
            value: main
          - name: GIT_SYNC_SSH
            value: "true"
          - name: GIT_SYNC_WAIT
            value: "60"
          - name: GIT_SYNC_ROOT
            value: /workspace
          - name: GIT_SYNC_DEST
            value: files
          - name: GIT_SYNC_ONE_TIME
            value: "true"
      volumes:
      - name: git-creds
        secret:
          secretName: git-creds
          defaultMode: 256
      - name: source
        emptyDir: {}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
