{{- range $name, $build := $.Values.builds }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "build name is required" $name }}
  labels:
    {{- include "imagebuilder.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "imagebuilder.labels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "imagebuilder.labels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "imagebuilder.serviceAccountName" $ }}
      restartPolicy: Always
      containers:
        - name: runner
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args:
          - "--runner"
          - "sleep=5"
          - "--runner"
          - "sync=30"
          - "--runner"
          - "build"
          - "--no-exit"
        - name: "{{ $name }}"
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args:
          - "--git-repo={{ required "git repo is required" $build.git.repo }}"
          - "--git-branch={{ required "git branch is required" $build.git.branch }}"
          - "--git-rev={{ required "git revision is required" $build.git.revision }}"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          securityContext:
            runAsUser: 0
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
